#!/bin/bash
ROLES=~/wordpress-ansible/roles
MYSQLDEFAULT_YML=$ROLES/mysql/defaults/main.yml.param
NEW_MYSQLDEFAULT_YML=$ROLES/mysql/defaults/main.yml

SERVERDEFAULT_YML=$ROLES/server/defaults/main.yml.param
NEW_SERVERDEFAULT_YML=$ROLES/server/defaults/main.yml

NEW_WP_MYSQL_DB=dbname1
NEW_WP_MYSQL_USER=dbuser1
NEW_WP_MYSQL_PASSWORD=DBPasswor1d
NEW_MY_SQL_ROOT_PASSWORD=root1

sed -e "s;%WP_MYSQL_DB%;$NEW_WP_MYSQL_DB;g" -e "s;%WP_MYSQL_USER%;$NEW_WP_MYSQL_USER;g" -e "s;%WP_MYSQL_PASSWORD%;$NEW_WP_MYSQL_PASSWORD;g" $MYSQLDEFAULT_YML > $NEW_MYSQLDEFAULT_YML

sed -e "s;%MY_SQL_ROOT_PASSWORD%;$NEW_MY_SQL_ROOT_PASSWORD;g" $SERVERDEFAULT_YML > $NEW_SERVERDEFAULT_YML 
